### ISSUE TITLE
Incorrect progress bar outline / alerts / active chip / badges states on Web Components

### ISSUE THREAD

**Issue by soniakaukonen** [trimble-oss/modus-web-components#1008]
See details https://github.com/trimble-oss/website-modus.trimble.com/issues/394

from the above link:

Progress bar:

- [x] Light and dark Mode Progress bar:  outline is Gray (`#6a6e79`) 6 both in Figma and XD, but indicates a non-palette color on style guide "border: 1px solid `#8c8b96`"

Alerts:

- [x] Dark mode dark Alert outline should be changed from Gray 10 to Gray 8 `#464B52`
- [x] The frame color of the secondary Alert is inconsistent (Gray 8 in both kits vs. Gray 6 on site). should be Gray 8 `#464B52`

Chips:

- [x] Dark mode active Chip/solid should be Trimble Dark Mode Blue `#019AEB`, it is currently Trimble blue on Style Guide. Both Figma and XD is `#019AEB`

Badges:

- [x] Light mode badges - warning badges have incorrect yellow on Style Guide. Currently on Yellow Dark. Both Figma and XD have correct Trimble Yellow `#FBAD26` with Trimble Gray label `#252A2E`
- [x] Dark mode - Dark badge label to be renamed to High Contrast

**Comment by soniakaukonen** [comment]
@msankaran0712 - I see this was incorrect here. Web components need to be changed to Gray 6.
